#!/bin/bash

# Anh Nguyen <anh.ng8@gmail.com>
# 2016-04-30
# MIT License

# This script takes in images from a folder and make a crossfade video from the images using ffmpeg.
# Make sure you have ffmpeg installed before running.

#----------------------------------------------------------------
# SETTINGS
input_dir="$1"  # Replace this by a path to your folder /path/to/your/folder
duration="$2"
n_files=10                        # Replace this by a number of images
files=`ls ${input_dir}/*.jpg | head -${n_files}`  # Change the file type to the correct type of your images
output_file="video.mp4"           # Name of output video
crossfade=0.9                     # Crossfade duration between two images
#----------------------------------------------------------------

# Making an ffmpeg script...
input=""
filters=""
output="[0:v]"

i=0

for f in ${files}; do
  input+=" -loop 1 -t ${duration} -i $f"

  next=$((i+1))
  if [ "${i}" -ne "$((n_files-1))" ]; then
    filters+=" [${next}:v][${i}:v]blend=all_expr='A*(if(gte(T,${crossfade}),1,T/${crossfade}))+B*(1-(if(gte(T,${crossfade}),1,T/${crossfade})))'[b${next}v];"
  fi

  if [ "${i}" -gt "0" ]; then
    output+="[b${i}v][${i}:v]"
  fi

  i=$((i+1))
done

output+="concat=n=$((i * 2 - 1)):v=1:a=0,format=yuv420p[v]\" -map \"[v]\" ${output_file}"

script="ffmpeg ${input} -filter_complex \"${filters} ${output}"

echo ${script}

# Run it
eval "${script}"
